version: "3"

services:
  nextcloud:
    image: "linuxserver/nextcloud"
    hostname: "nextcloud"
    container_name: "nextcloud"
    restart: "unless-stopped"
    ports:
      - "8080:443"
    volumes:
      - "./config:/config"
      - "./data:/data"
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ: "${TZ:-Europe/Zurich}"

  nextcloud-db:
    image: "mariadb"
    hostname: "nextcloud-db"
    container_name: "nextcloud-db"
    restart: "unless-stopped"
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_USER: "${MYSQL_USER:-nextcloud}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-nextcloud}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-nextcloud}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-nextcloud}"
