version: '2'

services:
  portainer:
    hostname: 'portainer'
    container_name: 'portainer'
    image: 'portainer/portainer-ce'
    command: ['-H', 'unix:///var/run/docker.sock']
    restart: 'unless-stopped'
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '9000:9000'

